FROM nginx:alpine

# Copy Angular build files
COPY frontend/dist/frontend/browser /usr/share/nginx/html

# Copy nginx config
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
